"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ES' | 'EN';

type LanguageContextType = {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations = {
  ES: {
    'nav.search': 'Descubre tu próxima suscripción...',
    'nav.catalog': 'Catálogo',
    'nav.about': 'Sobre Nosotros',
    'nav.support': 'Soporte',
    'nav.login': 'Entrar',
    'nav.dashboard': 'Mi Panel',
    'hero.title': 'Ahorra hasta 85% en IA, streaming y juegos premium.',
    'hero.desc': 'Descubre nuestra nueva tienda web y disfruta del mejor entretenimiento digital. Compra con total seguridad y recibe acceso inmediato a tus cuentas favoritas.',
    'cat.all': 'Todo',
    'cat.streaming': 'Streaming',
    'cat.ai': 'IA',
    'cat.music': 'Música',
    'cat.games': 'Juegos',
    'cat.recharges': 'Diamantes de Free Fire',
    'empty.search': 'No se encontraron productos para tu búsqueda.',
    'why.title': '¿Por qué elegirnos?',
    'why.exp.title': 'Calidad Garantizada',
    'why.exp.desc': 'Nos esforzamos por brindarte el mejor servicio, priorizando tu seguridad y satisfacción en cada compra.',
    'why.delivery.title': 'Entrega Inmediata',
    'why.delivery.desc': 'Recibe tu cuenta y credenciales automáticamente tras tu pago.',
    'why.warranty.title': 'Garantía Total',
    'why.warranty.desc': 'Cuentas 100% legales y garantizadas durante todo tu periodo.',
    'why.support.title': 'Soporte Dedicado',
    'why.support.desc': 'Atención personalizada para resolver cualquier inconveniente rápidamente.',
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'De las redes a tu pantalla',
    'about.desc1': '¡Hola! Somos el equipo de akiravs, dos colegas apasionados por acercar el mejor entretenimiento digital al mejor precio.',
    'about.desc2': 'Lo que empezó como ventas a través de redes, hoy evoluciona en esta plataforma oficial para brindarte mayor seguridad y comodidad. Nuestro compromiso sigue siendo el mismo: cuentas legales, precios accesibles y garantía total.',
    'ref.title': 'Referencias de Clientes Reales',
    'cart.add': 'Agregar al Carrito',
    'cart.title': 'Tu Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.subtotal': 'Subtotal',
    'cart.checkout.card': 'Pagar con Tarjeta',
    'cart.checkout.paypal': 'Pagar con PayPal',
    'modal.includes': '¿Qué incluye?',
    'product.month': '/ mes',
    'product.details': 'Ver más detalles',
    'product.stock.available': 'cuentas disponibles',
    'product.stock.out': 'Agotado',
    'product.stock.none': 'Sin Stock',
    'product.stock.ondemand': 'Bajo pedido',
    'dashboard.purchases': 'Mis Compras',
    'dashboard.purchases.empty': 'Aún no tienes suscripciones activas. ¡Explora el catálogo!',
    'dashboard.admin': 'Panel de Administrador',
    'dashboard.logout': 'Cerrar Sesión',
    'footer.desc': 'Tu tienda de confianza para servicios digitales premium.',
    'footer.links': 'Enlaces',
    'footer.legal': 'Legales',
    'footer.terms': 'Términos y Condiciones',
    'footer.privacy': 'Política de Privacidad',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.developed': 'Desarrollado por',
    'review.title': 'Opiniones de nuestros clientes',
    'review.leave': 'Dejar una opinión',
    'review.name': 'Tu nombre',
    'review.comment': 'Cuéntanos tu experiencia...',
    'review.submit': 'Publicar Opinión',
    'review.empty': 'Aún no hay opiniones. ¡Sé el primero en comentar!',
    'product.verify_id': 'Chat para recargar',
    'product.recharge.available': 'Disponible para Recarga',
    'product.recharge.request': 'Solicitar Recarga',
    'chat.title': 'Chat de Soporte',
    'chat.placeholder': 'Escribe tu mensaje...',
    'chat.send': 'Enviar',
    'chat.admin_title': 'Admin',
    'chat.user_title': 'Tú',
    'admin.chats.active': 'Chats Activos',
    'admin.chats.loading': 'Cargando chats...',
    'admin.chats.empty': 'No tienes chats activos.',
    'admin.chats.click_to_view': 'Clic para ver chat',
    'admin.chats.close_chat': 'Cerrar Chat',
    'admin.chats.delete_title': '¿Eliminar Chat?',
    'admin.chats.delete_desc': 'Esta acción no se puede deshacer.',
    'admin.chats.delete_cancel': 'Cancelar',
    'admin.chats.delete_confirm': 'Eliminar',
    'admin.chats.status_open': 'Abierto',
    'admin.chats.status_closed': 'Cerrado',
    'chat.support.name': 'Atención al Cliente',
    'chat.loading': 'Cargando...',
    'chat.welcome': '👋 ¡Hola! Soy el asistente de soporte. ¿En qué te puedo ayudar hoy?',
    'chat.quick.payment': 'Problema de pago',
    'chat.quick.account': 'Ayuda con cuenta',
    'chat.quick.other': 'Otra consulta',
    'chat.quick.ask_id': 'Pedir ID',
    'chat.quick.id_verified': 'ID Verificado',
    'chat.quick.processing': 'Procesando',
    'chat.quick.completed': 'Completada',
    'chat.btn.payment': '💰 Botón Pago',
    'chat.payment.approved': 'Recarga Aprobada',
    'chat.payment.pay_card': '💳 Pagar con Tarjeta',
    'chat.payment.processing': 'Procesando...',
    'chat.payment.error': 'Error. Intentar de nuevo',
    'widget.theme': 'Cambiar Tema',
    'widget.admin': 'Panel Admin',
    'widget.support': 'Soporte',
    'cart.checkout.finalize': 'Finalizar Compra',
    'checkout.title': 'Pago Seguro',
    'checkout.total': 'Total a pagar',
    'checkout.email': 'Correo electrónico para entrega',
    'checkout.email.placeholder': 'tu@correo.com',
    'checkout.method': 'Método de pago',
    'checkout.card': 'Tarjeta',
    'checkout.card.number': 'Número de Tarjeta',
    'checkout.card.expiry': 'Vencimiento',
    'checkout.card.cvv': 'CVV',
    'checkout.pay_btn': 'Pagar',
    'checkout.secure': 'Pagos encriptados de forma segura',
    'checkout.processing.title': 'Procesando pago...',
    'checkout.processing.desc': 'Por favor no cierres esta ventana',
    'checkout.success.title': '¡Pago Exitoso!',
    'checkout.success.desc': 'Tu compra se ha procesado correctamente. Te estamos redirigiendo a tu Dashboard donde podrás ver tus cuentas.',
    'checkout.error': 'Error al procesar el pago',
    'catalog.loading': 'Cargando productos...',
    'catalog.load_more': 'Ver más',
    'dashboard.order.verifying': 'Verificando Pago',
    'dashboard.order.active': 'Activa',
    'dashboard.order.verifying_desc1': 'Tu comprobante de transferencia está siendo verificado.',
    'dashboard.order.verifying_desc2': 'Tus credenciales aparecerán aquí pronto.',
    'dashboard.order.user': 'Usuario:',
    'dashboard.order.password': 'Contraseña:',
    'dashboard.order.profile': 'Perfil:',
    'dashboard.order.pin': 'PIN:',
    'dashboard.order.bought_on': 'Comprado el',
    'dashboard.order.renew': 'Renovar',
    'admin.tab.products': 'Productos',
    'admin.tab.reviews': 'Opiniones',
    'admin.tab.chats': 'Chats',
    'admin.tab.orders': 'Transferencias',
    'admin.orders.loading': 'Cargando órdenes pendientes...',
    'admin.orders.title': 'Transferencias Pendientes',
    'admin.orders.refresh': 'Actualizar',
    'admin.orders.empty': 'No hay transferencias pendientes de verificación.',
    'admin.orders.buyer': 'Comprador:',
    'admin.orders.price': 'Precio:',
    'admin.orders.date': 'Fecha:',
    'admin.orders.reserved': 'Cuenta Reservada (Oculta al usuario):',
    'admin.orders.receipt': 'Comprobante Adjunto:',
    'admin.orders.no_receipt': 'Sin comprobante',
    'admin.orders.reject': 'Rechazar',
    'admin.orders.approve': 'Aprobar Pago',
    'admin.orders.processing': 'Procesando...',
    'admin.orders.approve_title': '¿Aprobar transferencia?',
    'admin.orders.reject_title': '¿Rechazar transferencia?',
    'admin.orders.approve_desc': 'Si apruebas, la orden se marcará como pagada y el comprador verá sus contraseñas inmediatamente.',
    'admin.orders.reject_desc': 'Si rechazas, esta orden será eliminada permanentemente del sistema.',
    'admin.orders.email': 'Correo de la cuenta',
    'admin.orders.password': 'Contraseña',
    'admin.orders.profile': 'Perfil',
    'admin.orders.pin': 'PIN',
    'admin.prod.add_title': 'Añadir Nuevo Producto',
    'admin.prod.name': 'Nombre del Producto',
    'admin.prod.name_placeholder': 'Ej: Cuenta de Free Fire',
    'admin.prod.desc': 'Descripción',
    'admin.prod.desc_placeholder': 'Detalles de la cuenta o producto... (Máx 400 caracteres)',
    'admin.prod.price': 'Precio (USD)',
    'admin.prod.category': 'Categoría',
    'cat.ai_full': 'Inteligencia Artificial',
    'cat.games_full': 'Juegos (Gral)',
    'admin.prod.stock': 'Stock Inicial / Cuentas (Opcional)',
    'admin.prod.email_ph': 'Correo de la cuenta...',
    'admin.prod.pass_ph': 'Contraseña...',
    'admin.prod.add_btn': '+ Añadir',
    'admin.prod.bulk': 'O pegar lista masiva (correo:contraseña)',
    'admin.prod.color': 'Color de Fondo',
    'admin.prod.color_desc': 'El icono se generará automáticamente.',
    'admin.prod.image': 'Imagen (Opcional)',
    'admin.prod.image_file': 'Archivo seleccionado (Ignorando URL)',
    'admin.prod.image_url': 'Pegar URL externa...',
    'admin.prod.saving': 'Guardando...',
    'admin.prod.save': 'Guardar Producto',
    'footer.payment_methods': 'Métodos de Pago',
    'support.subtitle': 'Estamos aquí para ayudarte. Encuentra respuestas rápidas o contáctanos directamente a través de nuestros canales de atención.',
    'support.whatsapp.title': 'Soporte por WhatsApp',
    'support.whatsapp.desc': 'Respuestas rápidas para problemas con tus cuentas, pagos o acceso.',
    'support.whatsapp.btn': 'Enviar Mensaje',
    'support.email.title': 'Correo Electrónico',
    'support.email.desc': 'Escríbenos para dudas generales, facturación o consultas de negocios.',
    'support.email.btn': 'bonejohao60@gmail.com',
    'support.faq.title': 'Preguntas Frecuentes',
    'support.faq.1.q': '¿Cómo recibo mi cuenta después de pagar?',
    'support.faq.1.a': 'Inmediatamente después de que se confirme el pago a través de PayPal o Tarjeta de crédito, enviaremos los datos de acceso (correo y contraseña) al correo electrónico que proporcionaste durante la compra.',
    'support.faq.2.q': '¿Tienen garantía las cuentas?',
    'support.faq.2.a': 'Sí. Ofrecemos garantía durante todo el periodo que hayas contratado. Si la cuenta presenta problemas, contacta a nuestro soporte de WhatsApp y te daremos un reemplazo rápido.',
    'support.faq.3.q': '¿Puedo cambiar la contraseña de las cuentas?',
    'support.faq.3.a': 'Depende del producto. Algunas cuentas son compartidas para ofrecer el mejor precio (no se debe cambiar la clave), pero otras cuentas como las de Free Fire son 100% tuyas y puedes cambiar todos los datos de acceso.',
    'terms.title': 'Términos y Condiciones',
    'terms.1.title': '1. Aceptación de los Términos',
    'terms.1.desc': 'Al acceder y realizar compras en akiravs, aceptas estar sujeto a estos Términos y Condiciones. Si no estás de acuerdo con alguna parte de estos términos, te pedimos que no utilices nuestros servicios.',
    'terms.2.title': '2. Descripción del Servicio',
    'terms.2.desc': 'akiravs ofrece la venta de cuentas y perfiles digitales para plataformas de streaming, inteligencia artificial, videojuegos y otros servicios digitales. Todos los productos están sujetos a disponibilidad de inventario.',
    'terms.3.title': '3. Política de Cero Reembolsos (IMPORTANTE)',
    'terms.3.desc': 'Debido a la naturaleza digital de nuestros productos y para evitar el uso indebido de las cuentas, NO SE ACEPTAN REEMBOLSOS, CAMBIOS NI DEVOLUCIONES bajo ninguna circunstancia una vez que las credenciales de la cuenta han sido entregadas al cliente. Te recomendamos revisar cuidadosamente tu pedido antes de realizar el pago.',
    'terms.4.title': '4. Garantía Limitada',
    'terms.4.desc': 'Ofrecemos garantía únicamente en caso de que las credenciales entregadas no funcionen en el momento exacto de la entrega. El cliente debe notificar inmediatamente al soporte. La garantía no cubre bloqueos por mal uso, cambio de contraseñas no autorizados, o compartir cuentas a terceros.',
    'terms.5.title': '5. Uso Permitido',
    'terms.5.desc': 'Está estrictamente prohibido alterar los datos de la cuenta (correo, contraseña, perfiles o métodos de pago) a menos que se indique explícitamente que la cuenta es de propiedad total. El incumplimiento de esta norma resultará en la suspensión inmediata del servicio sin derecho a reclamo o reembolso.',
    'terms.6.title': '6. Cambios en los Términos',
    'terms.6.desc': 'Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigencia inmediatamente después de su publicación en el sitio web.',
    'privacy.title': 'Política de Privacidad',
    'privacy.desc': 'En akiravs, nos tomamos muy en serio la privacidad y protección de los datos personales de nuestros clientes. Esta Política de Privacidad describe cómo recopilamos, utilizamos y protegemos tu información.',
    'privacy.1.title': '1. Información que Recopilamos',
    'privacy.1.desc': 'Para ofrecer nuestros servicios, recopilamos la siguiente información personal: \n- Datos de contacto: Nombre, dirección de correo electrónico (a través del inicio de sesión con Google).\n- Datos de transacciones: Comprobantes de transferencia bancaria, identificadores de pago de PayPal.\n- Datos de la cuenta: Historial de compras y registros del chat de soporte técnico.',
    'privacy.2.title': '2. Uso de la Información',
    'privacy.2.desc': 'Utilizamos tu información exclusivamente para:\n- Procesar y entregar tus pedidos digitales de manera rápida y segura.\n- Brindarte soporte técnico y servicio al cliente a través de nuestro chat interno.\n- Notificarte sobre el estado de tu compra o verificación de tu pago.',
    'privacy.3.title': '3. Protección de Datos (Seguridad)',
    'privacy.3.desc': 'Implementamos medidas de seguridad avanzadas para mantener tu información personal a salvo. No almacenamos datos de tarjetas de crédito o débito en nuestros servidores, ya que utilizamos proveedores de pago externos (PayPal) que manejan esta información bajo estrictos protocolos de seguridad (PCI-DSS).',
    'privacy.4.title': '4. Compartir Información con Terceros',
    'privacy.4.desc': 'akiravs NUNCA vende, alquila o comercializa tu información personal a terceros. Solo compartiremos datos estrictamente necesarios con plataformas procesadoras de pagos (como PayPal) para poder autorizar la transacción.',
    'privacy.5.title': '5. Retención de Datos',
    'privacy.5.desc': 'Mantendremos la información de tus pedidos y compras en nuestra base de datos para que puedas acceder al historial y a las contraseñas de los productos que adquiriste en cualquier momento desde tu panel de usuario.',
    'privacy.6.title': '6. Contacto',
    'privacy.6.desc': 'Si tienes alguna pregunta sobre esta Política de Privacidad, no dudes en contactarnos a través de la sección de soporte.',
  },
  EN: {
    'nav.search': 'Discover your next subscription...',
    'nav.catalog': 'Catalog',
    'nav.about': 'About Us',
    'nav.support': 'Support',
    'nav.login': 'Login',
    'nav.dashboard': 'My Dashboard',
    'hero.title': 'Save up to 85% on premium AI, streaming, and gaming.',
    'hero.desc': 'Discover our new web store and enjoy the best digital entertainment. Shop securely and get instant access to your favorite accounts.',
    'cat.all': 'All',
    'cat.streaming': 'Streaming',
    'cat.ai': 'AI',
    'cat.music': 'Music',
    'cat.games': 'Games',
    'cat.recharges': 'Free Fire Diamonds',
    'empty.search': 'No products found for your search.',
    'why.title': 'Why Choose Us?',
    'why.exp.title': 'Guaranteed Quality',
    'why.exp.desc': 'We strive to provide the best service, prioritizing your security and satisfaction with every purchase.',
    'why.delivery.title': 'Instant Delivery',
    'why.delivery.desc': 'Receive your account and credentials automatically after payment.',
    'why.warranty.title': 'Total Warranty',
    'why.warranty.desc': '100% legal accounts guaranteed throughout your subscription period.',
    'why.support.title': 'Dedicated Support',
    'why.support.desc': 'Personalized attention to resolve any issues quickly.',
    'about.title': 'About Us',
    'about.subtitle': 'From social media to your screen',
    'about.desc1': 'Hello! We are the akiravs team, two colleagues passionate about bringing the best digital entertainment at the best price.',
    'about.desc2': 'What started as sales through social networks, today evolves into this official platform to provide greater security and comfort. Our commitment remains the same: legal accounts, affordable prices, and total warranty.',
    'ref.title': 'Real Customer References',
    'cart.add': 'Add to Cart',
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.checkout.card': 'Pay with Card',
    'cart.checkout.paypal': 'Pay with PayPal',
    'modal.includes': 'What is included?',
    'product.month': '/ month',
    'product.details': 'View details',
    'product.stock.available': 'accounts available',
    'product.stock.out': 'Out of Stock',
    'product.stock.none': 'No Stock',
    'product.stock.ondemand': 'On Demand',
    'dashboard.purchases': 'My Purchases',
    'dashboard.purchases.empty': 'You have no active subscriptions yet. Explore our catalog!',
    'dashboard.admin': 'Admin Dashboard',
    'dashboard.logout': 'Logout',
    'footer.desc': 'Your trusted store for premium digital services.',
    'footer.links': 'Links',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.rights': 'All rights reserved.',
    'footer.developed': 'Developed by',
    'review.title': 'Customer Reviews',
    'review.leave': 'Leave a review',
    'review.name': 'Your name',
    'review.comment': 'Tell us about your experience...',
    'review.submit': 'Post Review',
    'review.empty': 'No reviews yet. Be the first to comment!',
    'product.verify_id': 'Chat to Recharge',
    'product.recharge.available': 'Available for Recharge',
    'product.recharge.request': 'Request Recharge',
    'chat.title': 'Support Chat',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.admin_title': 'Admin',
    'chat.user_title': 'You',
    'admin.chats.active': 'Active Chats',
    'admin.chats.loading': 'Loading chats...',
    'admin.chats.empty': 'You have no active chats.',
    'admin.chats.click_to_view': 'Click to view chat',
    'admin.chats.close_chat': 'Close Chat',
    'admin.chats.delete_title': 'Delete Chat?',
    'admin.chats.delete_desc': 'This action cannot be undone.',
    'admin.chats.delete_cancel': 'Cancel',
    'admin.chats.delete_confirm': 'Delete',
    'admin.chats.status_open': 'Open',
    'admin.chats.status_closed': 'Closed',
    'chat.support.name': 'Customer Support',
    'chat.loading': 'Loading...',
    'chat.welcome': '👋 Hello! I am the support assistant. How can I help you today?',
    'chat.quick.payment': 'Payment issue',
    'chat.quick.account': 'Account help',
    'chat.quick.other': 'Other inquiry',
    'chat.quick.ask_id': 'Ask for ID',
    'chat.quick.id_verified': 'ID Verified',
    'chat.quick.processing': 'Processing',
    'chat.quick.completed': 'Completed',
    'chat.btn.payment': '💰 Payment Button',
    'chat.payment.approved': 'Recharge Approved',
    'chat.payment.pay_card': '💳 Pay with Card',
    'chat.payment.processing': 'Processing...',
    'chat.payment.error': 'Error. Try again',
    'widget.theme': 'Toggle Theme',
    'widget.admin': 'Admin Panel',
    'widget.support': 'Support',
    'cart.checkout.finalize': 'Checkout',
    'checkout.title': 'Secure Payment',
    'checkout.total': 'Total to pay',
    'checkout.email': 'Delivery email address',
    'checkout.email.placeholder': 'you@email.com',
    'checkout.method': 'Payment method',
    'checkout.card': 'Card',
    'checkout.card.number': 'Card Number',
    'checkout.card.expiry': 'Expiry',
    'checkout.card.cvv': 'CVV',
    'checkout.pay_btn': 'Pay',
    'checkout.secure': 'Payments securely encrypted',
    'checkout.processing.title': 'Processing payment...',
    'checkout.processing.desc': 'Please do not close this window',
    'checkout.success.title': 'Payment Successful!',
    'checkout.success.desc': 'Your purchase was processed successfully. You are being redirected to your Dashboard to view your accounts.',
    'checkout.error': 'Error processing payment',
    'catalog.loading': 'Loading products...',
    'catalog.load_more': 'See more',
    'dashboard.order.verifying': 'Verifying Payment',
    'dashboard.order.active': 'Active',
    'dashboard.order.verifying_desc1': 'Your transfer receipt is being verified.',
    'dashboard.order.verifying_desc2': 'Your credentials will appear here soon.',
    'dashboard.order.user': 'User:',
    'dashboard.order.password': 'Password:',
    'dashboard.order.profile': 'Profile:',
    'dashboard.order.pin': 'PIN:',
    'dashboard.order.bought_on': 'Purchased on',
    'dashboard.order.renew': 'Renew',
    'admin.tab.products': 'Products',
    'admin.tab.reviews': 'Reviews',
    'admin.tab.chats': 'Chats',
    'admin.tab.orders': 'Transfers',
    'admin.orders.loading': 'Loading pending orders...',
    'admin.orders.title': 'Pending Transfers',
    'admin.orders.refresh': 'Refresh',
    'admin.orders.empty': 'No pending transfers for verification.',
    'admin.orders.buyer': 'Buyer:',
    'admin.orders.price': 'Price:',
    'admin.orders.date': 'Date:',
    'admin.orders.reserved': 'Reserved Account (Hidden from user):',
    'admin.orders.receipt': 'Attached Receipt:',
    'admin.orders.no_receipt': 'No receipt',
    'admin.orders.reject': 'Reject',
    'admin.orders.approve': 'Approve Payment',
    'admin.orders.processing': 'Processing...',
    'admin.orders.approve_title': 'Approve transfer?',
    'admin.orders.reject_title': 'Reject transfer?',
    'admin.orders.approve_desc': 'If approved, the order will be marked as paid and the buyer will see their passwords immediately.',
    'admin.orders.reject_desc': 'If rejected, this order will be permanently deleted from the system.',
    'admin.orders.email': 'Account Email',
    'admin.orders.password': 'Password',
    'admin.orders.profile': 'Profile',
    'admin.orders.pin': 'PIN',
    'admin.prod.add_title': 'Add New Product',
    'admin.prod.name': 'Product Name',
    'admin.prod.name_placeholder': 'Ex: Free Fire Account',
    'admin.prod.desc': 'Description',
    'admin.prod.desc_placeholder': 'Account or product details... (Max 400 chars)',
    'admin.prod.price': 'Price (USD)',
    'admin.prod.category': 'Category',
    'cat.ai_full': 'Artificial Intelligence',
    'cat.games_full': 'Games (General)',
    'admin.prod.stock': 'Initial Stock / Accounts (Optional)',
    'admin.prod.email_ph': 'Account email...',
    'admin.prod.pass_ph': 'Password...',
    'admin.prod.add_btn': '+ Add',
    'admin.prod.bulk': 'Or paste bulk list (email:password)',
    'admin.prod.color': 'Background Color',
    'admin.prod.color_desc': 'Icon will be generated automatically.',
    'admin.prod.image': 'Image (Optional)',
    'admin.prod.image_file': 'File selected (Ignoring URL)',
    'admin.prod.image_url': 'Paste external URL...',
    'admin.prod.saving': 'Saving...',
    'admin.prod.save': 'Save Product',
    'footer.payment_methods': 'Payment Methods',
    'support.subtitle': 'We are here to help. Find quick answers or contact us directly through our support channels.',
    'support.whatsapp.title': 'WhatsApp Support',
    'support.whatsapp.desc': 'Quick answers for issues with your accounts, payments, or access.',
    'support.whatsapp.btn': 'Send Message',
    'support.email.title': 'Email',
    'support.email.desc': 'Write to us for general inquiries, billing, or business questions.',
    'support.email.btn': 'bonejohao60@gmail.com',
    'support.faq.title': 'Frequently Asked Questions',
    'support.faq.1.q': 'How do I receive my account after paying?',
    'support.faq.1.a': 'Immediately after the payment is confirmed via PayPal or Credit Card, we will send the access details (email and password) to the email address you provided during the purchase.',
    'support.faq.2.q': 'Do the accounts have a warranty?',
    'support.faq.2.a': 'Yes. We offer a warranty during the entire period you contracted. If the account presents issues, contact our WhatsApp support and we will give you a quick replacement.',
    'support.faq.3.q': 'Can I change the account password?',
    'support.faq.3.a': 'It depends on the product. Some accounts are shared to offer the best price (you must not change the password), but other accounts like Free Fire are 100% yours and you can change all access data.',
    'terms.title': 'Terms and Conditions',
    'terms.1.title': '1. Acceptance of Terms',
    'terms.1.desc': 'By accessing and making purchases on akiravs, you agree to be bound by these Terms and Conditions. If you disagree with any part of these terms, we ask that you do not use our services.',
    'terms.2.title': '2. Description of Service',
    'terms.2.desc': 'akiravs offers the sale of digital accounts and profiles for streaming platforms, artificial intelligence, video games, and other digital services. All products are subject to inventory availability.',
    'terms.3.title': '3. Zero Refund Policy (IMPORTANT)',
    'terms.3.desc': 'Due to the digital nature of our products and to prevent misuse of the accounts, NO REFUNDS, EXCHANGES, OR RETURNS ARE ACCEPTED under any circumstances once the account credentials have been delivered to the customer. We recommend carefully reviewing your order before making the payment.',
    'terms.4.title': '4. Limited Warranty',
    'terms.4.desc': 'We offer a warranty only if the delivered credentials do not work at the exact moment of delivery. The customer must notify support immediately. The warranty does not cover blocks due to misuse, unauthorized password changes, or sharing accounts with third parties.',
    'terms.5.title': '5. Permitted Use',
    'terms.5.desc': 'It is strictly forbidden to alter the account data (email, password, profiles, or payment methods) unless it is explicitly stated that the account is fully owned. Failure to comply with this rule will result in the immediate suspension of the service without the right to a claim or refund.',
    'terms.6.title': '6. Changes to Terms',
    'terms.6.desc': 'We reserve the right to modify these terms at any time. The changes will become effective immediately upon their publication on the website.',
    'privacy.title': 'Privacy Policy',
    'privacy.desc': 'At akiravs, we take the privacy and protection of our customers\' personal data very seriously. This Privacy Policy describes how we collect, use, and protect your information.',
    'privacy.1.title': '1. Information We Collect',
    'privacy.1.desc': 'To offer our services, we collect the following personal information: \n- Contact data: Name, email address (via Google login).\n- Transaction data: Bank transfer receipts, PayPal payment identifiers.\n- Account data: Purchase history and technical support chat logs.',
    'privacy.2.title': '2. Use of Information',
    'privacy.2.desc': 'We use your information exclusively to:\n- Process and deliver your digital orders quickly and securely.\n- Provide technical support and customer service through our internal chat.\n- Notify you about the status of your purchase or payment verification.',
    'privacy.3.title': '3. Data Protection (Security)',
    'privacy.3.desc': 'We implement advanced security measures to keep your personal information safe. We do not store credit or debit card data on our servers, as we use external payment providers (PayPal) that handle this information under strict security protocols (PCI-DSS).',
    'privacy.4.title': '4. Sharing Information with Third Parties',
    'privacy.4.desc': 'akiravs NEVER sells, rents, or commercializes your personal information to third parties. We will only share strictly necessary data with payment processing platforms (like PayPal) to authorize the transaction.',
    'privacy.5.title': '5. Data Retention',
    'privacy.5.desc': 'We will keep the information of your orders and purchases in our database so that you can access the history and passwords of the products you purchased at any time from your user panel.',
    'privacy.6.title': '6. Contact',
    'privacy.6.desc': 'If you have any questions about this Privacy Policy, do not hesitate to contact us through the support section.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ES');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language;
    if (savedLang && (savedLang === 'ES' || savedLang === 'EN')) {
      setLanguage(savedLang);
    }
  }, []);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'ES' ? 'EN' : 'ES';
      localStorage.setItem('lang', newLang);
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ES']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
